// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payment_Project_AP.Data;

#nullable disable

namespace Payment_Project_AP.Migrations
{
    [DbContext(typeof(CorporateBankingDBContext))]
    [Migration("20251030160124_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountStatusId")
                        .HasColumnType("int");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("TransactionIds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountStatusId");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("BankId");

                    b.HasIndex("ClientId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankId"));

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IFSC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("BankId");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Beneficiary", b =>
                {
                    b.Property<int>("BeneficiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeneficiaryId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("IFSC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeneficiaryId");

                    b.HasIndex("ClientId");

                    b.ToTable("Beneficiaries");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DocumentTypeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProofTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DocumentTypeTypeId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFSC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int?>("SalaryDisbursementId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ClientId");

                    b.HasIndex("SalaryDisbursementId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayeeAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PayerAccountId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("PayerAccountId");

                    b.HasIndex("PaymentStatusId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.SalaryDisbursement", b =>
                {
                    b.Property<int>("SalaryDisbursementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryDisbursementId"));

                    b.Property<bool>("AllEmployees")
                        .HasColumnType("bit");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DisbursementDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisbursementStatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SalaryDisbursementId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DisbursementStatusId");

                    b.ToTable("SalaryDisbursements");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.SalaryPayment", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("SalaryDisbursementId")
                        .HasColumnType("int");

                    b.Property<bool?>("Success")
                        .HasColumnType("bit");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("DetailId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SalaryDisbursementId");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.ToTable("SalaryPayments");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Support", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Supports");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int?>("SalaryDisbursementId")
                        .HasColumnType("int");

                    b.Property<string>("ToFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("SalaryDisbursementId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UserJoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("BankId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enums.AccountStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("StatusId");

                    b.ToTable("AccountStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Status = 0
                        },
                        new
                        {
                            StatusId = 2,
                            Status = 1
                        },
                        new
                        {
                            StatusId = 3,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enums.AccountType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TypeId");

                    b.ToTable("AccountTypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            Type = 0
                        },
                        new
                        {
                            TypeId = 2,
                            Type = 1
                        },
                        new
                        {
                            TypeId = 3,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enums.DocumentType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TypeId");

                    b.ToTable("DocumentTypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            Type = 0
                        },
                        new
                        {
                            TypeId = 2,
                            Type = 1
                        },
                        new
                        {
                            TypeId = 3,
                            Type = 2
                        },
                        new
                        {
                            TypeId = 4,
                            Type = 3
                        },
                        new
                        {
                            TypeId = 5,
                            Type = 4
                        },
                        new
                        {
                            TypeId = 6,
                            Type = 5
                        });
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enums.PaymentStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("StatusId");

                    b.ToTable("PaymentStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Status = 0
                        },
                        new
                        {
                            StatusId = 2,
                            Status = 1
                        },
                        new
                        {
                            StatusId = 3,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enums.TransactionType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TypeId");

                    b.ToTable("TransactionTypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            Type = 0
                        },
                        new
                        {
                            TypeId = 2,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enums.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Role = 0
                        },
                        new
                        {
                            RoleId = 2,
                            Role = 1
                        },
                        new
                        {
                            RoleId = 3,
                            Role = 2
                        });
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.BankUser", b =>
                {
                    b.HasBaseType("Payment_Project_AP.Models.Enitites.User");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefferalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("BankUser");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Client", b =>
                {
                    b.HasBaseType("Payment_Project_AP.Models.Enitites.User");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BankUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("KycVierified")
                        .HasColumnType("bit");

                    b.HasIndex("AccountId");

                    b.HasIndex("BankUserId");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Account", b =>
                {
                    b.HasOne("Payment_Project_AP.Models.Enums.AccountStatus", "AccountStatus")
                        .WithMany()
                        .HasForeignKey("AccountStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Payment_Project_AP.Models.Enums.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Payment_Project_AP.Models.Enitites.Bank", "Bank")
                        .WithMany("Accounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Payment_Project_AP.Models.Enitites.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.Navigation("AccountStatus");

                    b.Navigation("AccountType");

                    b.Navigation("Bank");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Beneficiary", b =>
                {
                    b.HasOne("Payment_Project_AP.Models.Enitites.Client", null)
                        .WithMany("Beneficiaries")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Document", b =>
                {
                    b.HasOne("Payment_Project_AP.Models.Enitites.Client", "Account")
                        .WithMany("Documents")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Payment_Project_AP.Models.Enums.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeTypeId");

                    b.Navigation("Account");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Employee", b =>
                {
                    b.HasOne("Payment_Project_AP.Models.Enitites.Client", "Client")
                        .WithMany("Employees")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Payment_Project_AP.Models.Enitites.SalaryDisbursement", null)
                        .WithMany("Employees")
                        .HasForeignKey("SalaryDisbursementId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Payment", b =>
                {
                    b.HasOne("Payment_Project_AP.Models.Enitites.Account", "PayerAccount")
                        .WithMany()
                        .HasForeignKey("PayerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Payment_Project_AP.Models.Enums.PaymentStatus", "PaymentStatus")
                        .WithMany()
                        .HasForeignKey("PaymentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayerAccount");

                    b.Navigation("PaymentStatus");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.SalaryDisbursement", b =>
                {
                    b.HasOne("Payment_Project_AP.Models.Enitites.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Payment_Project_AP.Models.Enums.PaymentStatus", "DisbursementStatus")
                        .WithMany()
                        .HasForeignKey("DisbursementStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("DisbursementStatus");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.SalaryPayment", b =>
                {
                    b.HasOne("Payment_Project_AP.Models.Enitites.Employee", "Employee")
                        .WithMany("SalaryPayment")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Payment_Project_AP.Models.Enitites.SalaryDisbursement", "SalaryDisbursement")
                        .WithMany("DisbursementDetails")
                        .HasForeignKey("SalaryDisbursementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Payment_Project_AP.Models.Enitites.Transaction", "Transaction")
                        .WithOne()
                        .HasForeignKey("Payment_Project_AP.Models.Enitites.SalaryPayment", "TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("SalaryDisbursement");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Transaction", b =>
                {
                    b.HasOne("Payment_Project_AP.Models.Enitites.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Payment_Project_AP.Models.Enitites.Payment", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId");

                    b.HasOne("Payment_Project_AP.Models.Enitites.SalaryDisbursement", "SalaryDisbursement")
                        .WithMany()
                        .HasForeignKey("SalaryDisbursementId");

                    b.HasOne("Payment_Project_AP.Models.Enums.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Payment");

                    b.Navigation("SalaryDisbursement");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.User", b =>
                {
                    b.HasOne("Payment_Project_AP.Models.Enitites.Bank", "Bank")
                        .WithMany("Users")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Payment_Project_AP.Models.Enums.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Client", b =>
                {
                    b.HasOne("Payment_Project_AP.Models.Enitites.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("Payment_Project_AP.Models.Enitites.BankUser", "BankUser")
                        .WithMany("Clients")
                        .HasForeignKey("BankUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("BankUser");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Bank", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Employee", b =>
                {
                    b.Navigation("SalaryPayment");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Payment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.SalaryDisbursement", b =>
                {
                    b.Navigation("DisbursementDetails");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.BankUser", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Payment_Project_AP.Models.Enitites.Client", b =>
                {
                    b.Navigation("Beneficiaries");

                    b.Navigation("Documents");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
